site_name: Oleg Nenashev - Self-Documentation
site_description: >-
  Whatever stuff about Oleg.
copyright: Copyright &copy; 2023 - Oleg Nenashev
docs_dir: _docs
repo_url: https://github.com/oleg-nenashev/oleg-nenashev
repo_name: Oleg's self-documentation site
edit_uri: edit/main/
site_url: https://oleg-nenashev.github.io/oleg-nenashev

# Build
site_dir: _site

# Theme
theme:
  name: material
  highlightjs: true
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    # NOT compatible qith toc.integrate
    # - navigation.indexes
    - navigation.path
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.expand
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  font:
    text: DM Sans
    code: Roboto Mono
  #favicon: TODO
  #logo: TODO
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/oleg-nenashev
      name: GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/oleg_nenashev
      name: Twitter/X
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/onenashev/
      name: LinkedIn
    - icon: fontawesome/brands/telegram
      link: https://t.me/onenashev
      name: Telegram
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@asciidwarf
      name: Mastodon
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/asciidwarf/
      name: Instagram
  analytics:
    # FIXME: Update when in Production
    #provider: google
    #property: TODO
  
nav:
  - Open Source:
      - Overview: open-source/README.md
  - Public Speaking:
    - Overview: speaking/README.md 
    - My talks: speaking/talks.md
    - Speaker Profile: speaking/profile.md
    - Invite me: speaking/invite-me.md
  - Work:
    - Want to hire me?: job/README.md
    - Public C.V.: https://docs.google.com/document/d/17nQnjqXoV9Irij_CX4XE87VoUXMHqY1MWVh2H7zry_8/edit?usp=sharing
  - More Links:
    - Education: education/README.md
    - Linktree: https://linktr.ee/onenashev
    - Let's meet: https://calendly.com/onenashev/virtual-coffee
    - GitHub Sponsors: https://github.com/sponsors/oleg-nenashev

plugins:
  - search
  - autorefs
  - macros
  - mkdocs-pdf
  # OpenGraphs
  - social:
      # custom_layouts_dir is commercial feature
#  - multirepo:
      # TODO: Change to True once works
#      cleanup: false
#      keep_docs_dir: true
#      nav_repos:
        
  - redirects:
      redirect_maps:
        
# Markdown
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: '#'
  - attr_list
